import os
import json
from typing import Dict, List, Tuple
import sys

# add project root directory to Python path
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(current_dir)  # add current directory (project root directory)

from LEGOs.Sleec.sleecParser import parse_sleec, check_input_red, check_input_conflict, check_input_concerns, parse_and_max_trace

def run_sleec_parser(sleec_file: str, time_window: int = 15) -> Tuple[List[str], List[Dict]]:
    """
    run LEGOs' sleecParser to get the trace that triggers the most rules
    
    Args:
        sleec_file: path of SLEEC file
        time_window: time window size (default 15)
        
    Returns:
        Tuple[List[str], List[Dict]]: return (triggered rules list, final trace)
    """
    try:
        # directly call parse_and_max_trace function
        output = parse_and_max_trace(sleec_file, tracetime=time_window)
        
        # save full output to file
        with open('parser_output.txt', 'w') as f:
            f.write(output)
            
        # read file and parse trace
        trace = []
        with open('parser_output.txt', 'r') as f:
            for line in f:
                if line.startswith("at time"):
                    # parse time and event
                    time_str, event = line.split(": ", 1)
                    time = int(time_str.replace("at time ", ""))
                    
                    # parse event and parameters
                    if "(" in event:
                        event_name = event.split("(")[0]
                        params_str = event[event.find("(")+1:event.find(")")]
                        params = {}
                        if params_str:
                            for param in params_str.split(", "):
                                if "=" in param:
                                    key, value = param.split("=")
                                    # convert boolean and number
                                    if value.lower() == "true":
                                        value = True
                                    elif value.lower() == "false":
                                        value = False
                                    else:
                                        try:
                                            value = int(value)
                                        except ValueError:
                                            value = value
                                    params[key] = value
                    else:
                        event_name = event.strip()
                        params = {}
                    
                    trace.append({
                        "time": time,
                        "event": event_name,
                        "params": params
                    })
        
        return ["Trace generated"], trace  # for simplicity, we do not parse specific rules
        
    except Exception as e:
        print(f"Error running LEGOS parser: {str(e)}")
        return [], []

def convert_trace_to_lts(trace: List[Dict]) -> str:
    """
    convert trace generated by LEGOs to LTS format
    
    Args:
        trace: trace generated by LEGOs
        
    Returns:
        str: LTS format string
    """
    # calculate number of transitions
    transitions = len(trace)
    
    # build LTS string
    lts = [f"des (0,{transitions},{transitions})"]
    
    # add each transition
    for i, event in enumerate(trace):
        # build parameter string
        params = []
        for key, value in event["params"].items():
            params.append(f"{key}={value}")
        params_str = ", ".join(params)
        
        # build full transition label
        if params:
            label = f'{event["event"]}({params_str}, time={event["time"]})'
        else:
            label = f'{event["event"]}(time={event["time"]})'
            
        # add transition
        lts.append(f'({i}, "{label}", {i+1})')
    
    return "\n".join(lts)

def generate_lts_from_sleec(sleec_file: str, time_window: int = 15, rule_ids: List[str] = None) -> bool:
    """
    generate trace from SLEEC file
    
    Args:
        sleec_file: path of SLEEC file
        time_window: time window size
        rule_ids: list of rule IDs to be triggered (optional)
        
    Returns:
        bool: whether the trace is successfully generated
    """
    try:
        # run LEGOs parser to generate trace
        if rule_ids:
            output = parse_and_max_trace(sleec_file, target_rule_ids=rule_ids, tracetime=time_window)
        else:
            output = parse_and_max_trace(sleec_file, tracetime=time_window)
        
        # save full output to file
        with open('parser_output.txt', 'w') as f:
            f.write(output)
            
        return True
            
    except Exception as e:
        print(f"Error running LEGOS parser: {str(e)}")
        return False 