#!/usr/bin/env python3
"""
Single-file augmentation runner.

Inputs:
  - A trace text file (e.g., generated by legos_integration.py)
  - A JSON array from extract_context.py (system_agent/interacting_agent/user/location/time entries)

Behaviour:
  - Uses extracted system agent/interacting agent/user/location terms for measure annotations
  - Uses extracted time entries ONLY to choose the scenario start time (CLOCK)
  - Keeps event names unchanged; no external events or ad-hoc dimensions
  - Saves scene timeline and a simple LEGOs-style event/measure trace; OpenAI GPT only
"""

from __future__ import annotations

import argparse
import os
import json
import re
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent
from typing import Dict, List, Optional

from openai import OpenAI


# ------------------------------
# Models / configuration
# ------------------------------


@dataclass
class AugmentedArtifacts:
    """Structured representation of an augmented response (scenes only)."""

    full_response: str
    scenes: str


@dataclass
class AugmentationConfig:
    """Minimal config: fixed measure domain and scenario start clock."""

    domain_measures: List[Dict]
    start_clocks: List[str]
    additional_notes: Optional[str] = None


# ------------------------------
# IO helpers
# ------------------------------


def load_input(path: str | Path) -> str:
    data = Path(path).read_text(encoding="utf-8")
    if not data.strip():
        raise ValueError(f"Input file '{path}' is empty.")
    return data


def save_artifacts(
    *,
    artifacts: AugmentedArtifacts,
    output_dir: str | Path = ".",
    trace_lines: List[tuple],
    start_clocks: List[str],
    domain_measures: List[Dict],
) -> Dict[str, Path]:
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    scenes_path = output_path / "augment_scene.txt"
    scenes_path.write_text(artifacts.scenes, encoding="utf-8")

    legos_trace_path = output_path / "legos_augment_trace.txt"
    legos_trace = _format_legos_trace_with_original(
        artifacts.scenes,
        trace_lines,
        start_clocks,
        domain_measures,
    )
    legos_trace_path.write_text(legos_trace, encoding="utf-8")

    return {"scenes": scenes_path, "legos_trace": legos_trace_path}


# ------------------------------
# Parsing helpers
# ------------------------------


_SCENE_PATTERN = re.compile(r"Scene Label and Time:\s*(.*)$", re.DOTALL | re.IGNORECASE)


def _clean_block(text: Optional[str]) -> str:
    if not text:
        return ""
    lines = [line.strip() for line in text.strip().splitlines() if line.strip()]
    return "\n".join(lines)


def parse_augmented_response(response: str) -> AugmentedArtifacts:
    scene_match = _SCENE_PATTERN.search(response)
    scenes = _clean_block(scene_match.group(1)) if scene_match else _clean_block(response)

    return AugmentedArtifacts(
        full_response=response.strip(),
        scenes=scenes,
    )


def _parse_scene_info(scenes: str) -> List[tuple]:
    scene_lines = [line.strip() for line in scenes.splitlines() if line.strip()]
    # Updated regex to support optional seconds: HH:MM or HH:MM:SS
    pattern = re.compile(r"Scene\s+(\d+):\s*(.*?)(\b[0-2]?\d:[0-5]\d(?::[0-5]\d)?\b)?", re.IGNORECASE)
    info: List[tuple] = []
    for line in scene_lines:
        match = pattern.search(line)
        label = ""
        clock = ""
        if match:
            label = (match.group(2) or "").strip()
            clock = (match.group(3) or "").strip()
        if not label:
            label = line
        info.append((label, clock))
    return info


def _collect_domain_terms(domain_measures: List[Dict], category: str) -> List[str]:
    terms: List[str] = []
    for entry in domain_measures:
        if entry.get("category") != category:
            continue
        term = (entry.get("term") or entry.get("description") or "").strip().lower()
        if term:
            terms.append(term)
    return terms


def _format_legos_trace_with_original(
    scenes: str,
    trace_lines: List[tuple],
    start_clocks: List[str],
    domain_measures: List[Dict],
) -> str:
    """
    Insert augmented measures alongside original trace timing.
    Output keeps original `at time X:` lines and appends a Measure at same X using scene info.
    CLOCK values derive from the provided start clock plus the trace offset.
    """
    output_lines: List[str] = []
    scene_info = _parse_scene_info(scenes)

    def _parse_clock_to_seconds(clock: str) -> int:
        # Handle HH:MM or HH:MM:SS
        match = re.match(r"^([0-2]?\d):([0-5]\d)(?::([0-5]\d))?$", clock)
        if not match:
            return 0
        h = int(match.group(1))
        m = int(match.group(2))
        s = int(match.group(3)) if match.group(3) else 0
        return h * 3600 + m * 60 + s

    def _seconds_to_clock(seconds: int) -> str:
        seconds = seconds % (24 * 3600)
        h = seconds // 3600
        m = (seconds % 3600) // 60
        s = seconds % 60
        return f"{h:02d}:{m:02d}:{s:02d}"

    # Prefer LLM-provided scene clock; else fall back to earliest candidate from domain.
    base_seconds = 0
    for _, clk in scene_info:
        if clk:
            base_seconds = _parse_clock_to_seconds(clk)
            break
    if base_seconds == 0 and start_clocks:
        base_seconds = _parse_clock_to_seconds(start_clocks[0])

    system_agent_terms = _collect_domain_terms(domain_measures, "system_agent")
    interacting_terms = _collect_domain_terms(domain_measures, "interacting_agent")
    user_terms = _collect_domain_terms(domain_measures, "user")
    location_terms = _collect_domain_terms(domain_measures, "location")
    scene_idx = 0
    for time_val, content, is_measure in trace_lines:
        output_lines.append(f"at time {time_val}: {content}")
        if is_measure:
            continue
        label = scene_info[scene_idx][0] if scene_idx < len(scene_info) else "scene"
        clock = scene_info[scene_idx][1] if scene_idx < len(scene_info) else ""

        # If LLM provided a clock for the scene, use it (parsed to seconds then formatted back to ensure HH:MM:SS)
        # Otherwise, calculate from base_seconds + time_val (assuming time_val is seconds)
        if clock:
            measure_clock = _seconds_to_clock(_parse_clock_to_seconds(clock))
        else:
            measure_clock = _seconds_to_clock(base_seconds + time_val)

        label_lower = label.lower()
        matched_interacting = [t for t in interacting_terms if t in label_lower]
        matched_users = [t for t in user_terms if t in label_lower]

        interacting_token = "+".join(matched_interacting[:2]) if matched_interacting else None
        user_token = "+".join(matched_users[:2]) if matched_users else None
        location_token = next(
            (t for t in location_terms if t in label_lower),
            location_terms[0] if location_terms else "location",
        )
        agent_token = next(
            (t for t in system_agent_terms if t in label_lower),
            system_agent_terms[0] if system_agent_terms else "system",
        )
        measure_fields = [
            f"clock={measure_clock}",
            f"system_agent={agent_token}",
        ]
        if interacting_token:
            measure_fields.append(f"interacting_agents={interacting_token}")
        if user_token:
            measure_fields.append(f"users={user_token}")
        measure_fields.append(f"location={location_token}")

        output_lines.append(f"at time {time_val}: Measure({', '.join(measure_fields)})")
        scene_idx += 1

    return "\n".join(output_lines)


# ------------------------------
# Prompt builder
# ------------------------------


_BASE_REQUIREMENTS = dedent(
    """
    ## Core Requirements
    1. Produce only the scene timeline (`Scene Label and Time`), ordered by CLOCK.
    2. Each scene is a short, fluent sentence in natural language (present tense) explaining how the SYSTEM AGENT interacts with INTERACTING AGENTS/USERS at a LOCATION at that time.
       Avoid template phrasing like "performs <EventName>" or raw camel-case event names; paraphrase event names while preserving their meaning.
    3. Keep event semantics consistent with the original trace; do not invent new events.
    4. Use the fixed measure domain when referencing system agent/interacting agents/users/locations in the scene labels.
    5. CLOCK must start from the provided scenario time and stay monotonic.
    """
).strip()

_DOMAIN_CONSTRAINTS = dedent(
    """
    ## Domain Constraints
    - Do NOT invent new events or measures. Use only the provided measure domain (system agent/interacting agent/user/location) when referencing actors/places.
    - You may paraphrase event names into natural language. If you mention the event name explicitly, keep it unchanged.
    - If the original trace uses `time=X` pseudo annotations, preserve relative ordering via the CLOCK guidance.
    - Measures are not standalone events; they are attached to the event at the same `at time X`.
    - Any line starting with `Measure(` is metadata for the preceding event and should NEVER be treated as a scene.
    """
).strip()


def _measure_domain_section(domain_measures: list) -> str:
    buckets = {"system_agent": [], "interacting_agent": [], "user": [], "location": []}
    for entry in domain_measures:
        category = entry.get("category")
        if category not in buckets:
            continue
        term = (entry.get("term") or entry.get("description") or "").strip()
        description = (entry.get("description") or "").strip()
        direct = "direct" if entry.get("isDirect") else "inferred"
        buckets[category].append(f"- {term}: {description} ({direct})")

    sections: List[str] = ["## Fixed Measure Domain (only use these)"]
    if not any(buckets.values()):
        sections.append("- (none supplied)")
    else:
        for category in ("system_agent", "interacting_agent", "user", "location"):
            if not buckets[category]:
                continue
            heading = category.replace("_", " ").title()
            sections.append(f"### {heading}")
            sections.extend(buckets[category])

    return "\n".join(sections).strip()


def _clock_section(start_clocks: List[str]) -> str:
    start_list = ", ".join(start_clocks)
    primary = start_clocks[0]
    return dedent(
        f"""
        ## CLOCK Guidance
        - Pick ONE start time from the candidates: {start_list}. Use it consistently (e.g., Scene 1: ... {primary}).
        - If you set a scene-specific HH:MM, prefer one of the candidates above. Otherwise derive CLOCK from the chosen start time plus `at time` offsets.
        - Keep CLOCK monotonic and realistic across transitions.
        - Do NOT invent new absolute start times. Map any pseudo `time=X` to CLOCK increments consistent with seconds.
        - Do NOT add `time=` measures; only CLOCK annotations.
        """
    ).strip()


def build_prompt(trace_text: str, config: AugmentationConfig) -> str:
    sections: List[str] = []

    header = dedent(
        f"""
        TASK: Produce a scene timeline using the fixed domain below.

        Input Trace:
        {trace_text.strip()}
        """
    ).strip()
    sections.append(header)

    sections.append(_BASE_REQUIREMENTS)
    sections.append(_DOMAIN_CONSTRAINTS)
    sections.append(_clock_section(config.start_clocks))
    sections.append(_measure_domain_section(config.domain_measures))

    if config.additional_notes:
        sections.append("## Additional Notes\n" + config.additional_notes.strip())

    sections.append(
        dedent(
            """
            ## Output Format
            Scene Label and Time:
            Scene 1: <natural sentence describing system agent + interacting agents/users at a location> <HH:MM:SS>
            Scene 2: ...
            (Never list raw Measure(...) lines as scenes; they are metadata for the preceding event.)
            """
        ).strip()
    )

    return "\n\n".join(section for section in sections if section)


# ------------------------------
# LLM call
# ------------------------------


def call_llm(
    api_key: Optional[str],
    prompt: str,
    *,
    model: Optional[str] = None,
    temperature: float = 0.2,
    top_p: float = 0.9,
) -> str:
    if model is None:
        model = "gpt-4"

    resolved_key = api_key or os.getenv("OPENAI_API_KEY")
    if not resolved_key:
        raise RuntimeError("API key not provided; set --api-key or OPENAI_API_KEY.")

    client = OpenAI(api_key=resolved_key)

    system_prompt = (
        "You are an expert in formal behaviour modelling. "
        "Always follow the requested output format exactly."
    )

    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt},
        ],
        max_completion_tokens=2048,
        temperature=temperature,
        top_p=top_p,
        stream=False,
    )

    message = response.choices[0].message.content if response.choices else ""
    if not message:
        raise RuntimeError("Language model returned an empty response.")

    return message.strip()


# ------------------------------
# CLI helpers
# ------------------------------


TIME_REGEX = re.compile(r"\b([01]?\d|2[0-3]):([0-5]\d)(?::([0-5]\d))?\b")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Augment a trace using extracted measure domain cues.")
    parser.add_argument("input", type=Path, help="Path to the input trace file.")
    parser.add_argument(
        "--measure-domain",
        type=Path,
        required=True,
        help=(
            "JSON array output from extract_context.py "
            "(system_agent/interacting_agent/user/location/time). Time entries provide scenario start CLOCK."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("."),
        help="Directory to store augmentation artefacts.",
    )
    parser.add_argument(
        "--api-key",
        help="API key for the language model (optional; falls back to OPENAI_API_KEY env var).",
    )
    parser.add_argument("--model", default="gpt-5.1-2025-11-13", help="OpenAI model name (e.g., gpt-5.1-2025-11-13).")
    parser.add_argument("--temperature", type=float, default=0.2, help="Sampling temperature.")
    return parser.parse_args()


def _load_measure_domain(path: Path) -> list:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        raise SystemExit(f"Failed to read measure-domain file {path}: {exc}") from exc

    if not isinstance(data, list):
        raise SystemExit(f"Measure-domain file {path} must contain a JSON array.")
    return data


def _derive_start_clocks(domain_measures: list) -> List[str]:
    clocks: List[str] = []
    for entry in domain_measures:
        if entry.get("category") != "time":
            continue
        text = f"{entry.get('description', '')} {entry.get('term', '')}"
        for match in TIME_REGEX.finditer(text):
            value = match.group(0)
            if value not in clocks:
                clocks.append(value)
    if not clocks:
        raise SystemExit("Measure-domain file must include at least one time entry with HH:MM for scenario start.")
    # Sort by HH:MM numeric for stability
    def _to_minutes(t: str) -> int:
        parts = t.split(":")
        return int(parts[0]) * 60 + int(parts[1])

    clocks.sort(key=_to_minutes)
    return clocks


TRACE_LINE_PATTERN = re.compile(r"^\s*at time\s+(\d+):\s*(.+)$", re.IGNORECASE)


def _parse_trace_lines(trace_text: str) -> List[tuple]:
    lines: List[tuple] = []
    for raw in trace_text.splitlines():
        match = TRACE_LINE_PATTERN.match(raw)
        if not match:
            continue
        time_val = int(match.group(1))
        content = match.group(2).strip()
        is_measure = content.lower().startswith("measure")
        lines.append((time_val, content, is_measure))
    return lines


def main() -> None:
    args = _parse_args()

    domain_measures = _load_measure_domain(args.measure_domain)
    start_clocks = _derive_start_clocks(domain_measures)
    config = AugmentationConfig(domain_measures=domain_measures, start_clocks=start_clocks)

    trace_text = load_input(args.input)
    trace_lines = _parse_trace_lines(trace_text)
    if not trace_lines:
        raise SystemExit("Input trace must contain lines like 'at time X: <event>'.")
    prompt = build_prompt(trace_text, config)

    response = call_llm(
        args.api_key,
        prompt,
        model=args.model,
        temperature=args.temperature,
    )

    artifacts = parse_augmented_response(response)
    saved = save_artifacts(
        artifacts=artifacts,
        output_dir=args.output_dir,
        trace_lines=trace_lines,
        start_clocks=start_clocks,
        domain_measures=domain_measures,
    )

    print("Augmentation complete. Artefacts written to:")
    for label, path in saved.items():
        print(f"- {label}: {path}")


if __name__ == "__main__":
    main()
